jQuery.fn.sanitize=function(){return $(this[0]).val().toLowerCase().replace(/-+/g,"").replace(/\s+/g,"-").replace(/[^a-z0-9-]/g,"")};function addslashes(a){return(a+"").replace(/[\\"']/g,"\\$&").replace(/\u0000/g,"\\0")}
function gaClickTrack(){$(".track-click").gaTrackEventUnobtrusive({useEvent:!0,useLabel:!0,event:"click",complete:function(a,b){"_blank"===a.attr("target")?(""!=$.trim(a.attr("href"))&&(url=a.attr("href")),window.open(url,"_blank"),b.preventDefault()):(b.preventDefault(),setTimeout(function(){void 0===a.attr("ga-nolink")&&(window.location.href=b.currentTarget.href)},800));}})}gaClickTrack();
function nonInteractiveTracking(a,b,d,c){"undefined"===typeof c&&(c=null);$.ga.trackEvent({category:a,action:b,label:d,value:c,nonInteractive:!1})};
function createCookie(e,o,n){var t;if(n){var i=new Date;i.setTime(i.getTime()+24*n*60*60*1e3),t="; expires="+i.toGMTString()}else t="";document.cookie=encodeURIComponent(e)+"="+encodeURIComponent(o)+t+"; path=/"}
function readCookie(n){for(var e=encodeURIComponent(n)+"=",o=document.cookie.split(";"),t=0;t<o.length;t++){for(var r=o[t];" "===r.charAt(0);)r=r.substring(1,r.length);if(0===r.indexOf(e))return decodeURIComponent(r.substring(e.length,r.length))}return null}
function eraseCookie(e){createCookie(e,"",-1)}
function interactiveTracking(a,b,d,c){"undefined"===typeof c&&(c=null);$.ga.trackEvent({category:a,action:b,label:d,value:c,nonInteractive:1})};
function exeTrackingSearch(c,e,n){$.ajax({type:"POST",dataType:"json",url:"tracking-search-secondary"+e+"&location="+n,success:function(c){},error:function(c){}})}function trackingSearch(c,e,n){setTimeout(exeTrackingSearch(c,e,n),1e3)}
function trackingLink(_this,a,b,c){_gaq.push(['_set','hitCallback',function(){window.location.href=_this;}]);_gaq.push(['_trackEvent',a,b,c]);}
function check_password(a,b){b="undefined"!=typeof b&&b;var c,e,f,i,d=0,g="",h=0,k="white";if(e=a.length,a.match(/[a-z]/)&&(d+=26),a.match(/[A-Z]/)&&(d+=26),a.match(/[0-9]/)&&(d+=10),a.match(/[\W_]/)&&(d+=33),1==b)for(i=0;i<e;i++){for(var m=0,n=i+1;n<e;n++)a.charAt(i)==a.charAt(n)&&(m+=1);m<2&&(g+=a.charAt(i))}else g=a;for(f=g.length,c=Math.pow(d,f),i=c;i>=8;)h+=1,i/=8;h>50&&(h=50),0==h?strDesc="Sangat lemah":h<=7?(strDesc="Lemah",k="Red"):h<=16?(strDesc="Cukup",k="Orange"):h<=20?(strDesc="Baik",k="yellow"):h<=30?(strDesc="Kuat",k="GreenYellow"):h>30&&(strDesc="Sangat kuat",k="Green");var o={value:h,barColor:k,strDesc:strDesc};return o}
function getParameterByName(a,b){b||(b=window.location.href),a=a.replace(/[\[\]]/g,"\\$&");var c=new RegExp("[?&]"+a+"(=([^&#]*)|&|#|$)"),d=c.exec(b);return d?d[2]?decodeURIComponent(d[2].replace(/\+/g," ")):"":null}
function getTrackAdskom(){console.log("call getTrackAdskom, init var"),$.ajax({url:"//ssp.adskom.com/tags/third-party-async/MzFlMDBjNzktOWU3Yi00ZDZkLTg1OTUtYmI3ZmU4MjYzY2Nh",async:!0,dataType:"script"}),$.ajax({url:"//ssp.adskom.com/ak-dco.js",async:!0,dataType:"script",id:"__akcr"}),window.akcr=window.akcr||[],console.log("account : "+adskom_account),console.log("email : "+adskom_email),console.log("type : "+adskom_type),console.log("id : "+adskom_trxid),console.log("item id : "+adskom_id),console.log("item price : "+adskom_price),window.akcr.push({event:"setAccount",account:"undefined"!=typeof adskom_account&&null!==adskom_account?adskom_account:""},{event:"setHashedEmail",email:"undefined"!=typeof adskom_email&&null!==adskom_email?adskom_email:""},{event:"setSiteType",type:"undefined"!=typeof adskom_type&&null!==adskom_type?adskom_type:""},{event:"trackTransaction",id:"undefined"!=typeof adskom_trxid&&null!==adskom_trxid?adskom_trxid:"",sales_channel:"phone",item:[{id:"undefined"!=typeof adskom_id&&null!==adskom_id?adskom_id:"",price:"undefined"!=typeof adskom_price&&null!==adskom_price?adskom_price:"",quantity:1}]})}
function remarketingTrack(){goog_snippet_vars=function(){var o=window;o.google_conversion_id=966563937,o.google_conversion_label="5l15CNDNuWMQ4bDyzAM",o.google_remarketing_only=!1},goog_report_conversion=function(o){goog_snippet_vars(),window.google_conversion_format="3";var n=new Object;n.onload_callback=function(){"undefined"!=typeof o&&(window.location=o)};var e=window.google_trackConversion;"function"==typeof e&&e(n)},$.ajax({url:"//www.googleadservices.com/pagead/conversion_async.js",dataType:"script"})}
function getTrackAdskomSubmit(a,t,e,c,s,i){$.ajax({url:"//ssp.adskom.com/tags/third-party-async/MzFlMDBjNzktOWU3Yi00ZDZkLTg1OTUtYmI3ZmU4MjYzY2Nh",async:!0,dataType:"script"}),$.ajax({url:"//ssp.adskom.com/ak-dco.js",async:!0,dataType:"script",id:"__akcr"}),window.akcr=window.akcr||[],window.akcr.push({event:"setAccount",account:a},{event:"setHashedEmail",email:t},{event:"setSiteType",type:e},{event:"trackTransaction",id:c,sales_channel:"form",item:[{id:s,price:i,quantity:1}]})}